const CURRENCY_MAX = 9999999
const MIN_NUMBER_OF_CASSETTES = 2
const MAX_NUMBER_OF_CASSETTES = 4
const WALLET_SCORING_DEFAULT_THRESHOLD = 9

const AUTOMATIC = 'automatic'
const MANUAL = 'manual'

export {
  CURRENCY_MAX,
  MIN_NUMBER_OF_CASSETTES,
  MAX_NUMBER_OF_CASSETTES,
  AUTOMATIC,
  MANUAL,
  WALLET_SCORING_DEFAULT_THRESHOLD
}
