module Css.Classes exposing (..)



type CssClasses
    = Layout
    | Main
    | PaneWrapper
    | LeftPane
    | ContentPane
    | NavBar
    | MainLeft
    | MainRight
    | NavBarItemActive
    | NavBarCategoryContainer
    | NavBarCategory
    | NavBarRoute
    | Container
    | Content
    | CryptoTabs
    | CryptoTab
    | CryptoTabsActive
    | SectionLabel
    | ConfigTable
    | ConfigTableGlobalRow
    | ConfigContainer
    | TopDisplay
    | BottomDisplay
    | MultiDisplay
    | ShortCell
    | MediumCell
    | LongCell
    | TextCell
    | FormRow
    | Button
    | ButtonRow
    | Active
    | BasicInput
    | BasicInputDisabled
    | BasicInputReadOnly
    | CellDisabled
    | NoInput
    | Component
    | FocusedComponent
    | InvalidComponent
    | TableButton
    | Fail
    | Success
    | StatusBar
    | InvalidGroup
    | NumberColumn
    | DirectionColumn
    | TruncatedColumn
    | DateColumn
    | TxTable
    | InputContainer
    | UnitDisplay
    | EmptyTable
    | Saving
    | Enabled
    | Disabled
    | TxId
    | TxDate
    | TxMachine
    | TxAmount
    | TxFiat
    | TxCrypto
    | TxPhone
    | TxAddress
    | TxCancelled
    | QrCode
    | CashOut
    | CashIn
    | ReadOnly
    | CryptoAddress
    | BalanceSection
    | Textarea
    | SelectizeAccount
    | SelectizeFiatCurrency
    | SelectizeCryptoCurrency
    | SelectizeLanguage
    | SelectizeCountry
    | SelectizeOnOff
